import { openRollDialog, sendRollToChat } from "../workflows/rolls.mjs";
import { rollCurse, purify } from "../workflows/curse.mjs";
import { OPTIONS_BACKGROUND, OPTIONS_PRIDE, OPTIONS_ONMYOUJI } from "../workflows/static-options.mjs";

function buildLocalizedOptionsMap(options) {
  return new Map(options.map((opt) => [String(opt.value), game.i18n.localize(opt.labelKey)]));
}

function classifyResult(value) {
  const v = Number(value ?? 0);
  if (v >= 6) return game.i18n.localize("OCHO.Result.SuccessTotal");
  if (v >= 4) return game.i18n.localize("OCHO.Result.SuccessComp");
  if (v >= 2) return game.i18n.localize("OCHO.Result.FailComp");
  return game.i18n.localize("OCHO.Result.FailTotal");
}

function classifyResultCss(value) {
  const v = Number(value ?? 0);
  if (v >= 6) return "is-great";
  if (v >= 4) return "is-mixed";
  if (v >= 2) return "is-bad";
  return "is-awful";
}

function clampNumber(n, min, max, fallback=min) {
  const v = Number(n);
  if (!Number.isFinite(v)) return fallback;
  return Math.max(min, Math.min(max, v));
}

function applyCursedAppearance(roll) {
  const dice = Array.isArray(roll?.dice) ? roll.dice : [];
  for (const d of dice) {
    const flavor = String(d?.options?.flavor ?? "").toLowerCase();
    if (!flavor.includes("maldito")) continue;

    d.options = d.options ?? {};
    d.options.colorset = d.options.colorset ?? "ocho-maldicion";
    d.options.appearance = d.options.appearance ?? {
      background: "#b00020",
      foreground: "#ffffff",
      outline: "#1a1a1a",
      edge: "#1a1a1a"
    };
  }
}

export class OchoLanzasActor extends Actor {
  // Override prepareBaseData to apply dynamic checks before rendering
  prepareBaseData() {
    super.prepareBaseData();
    if (this.type === "character") {
      const min = this.system.curseMin;
      // We clamp the actual cur value in memory (not to DB) for rendering purposes
      if (this.system.curseCount < min) {
        this.system.curseCount = min;
      }
    }
  }

  async enforceCurseMin() {
    if (this.type !== "character") return;
    const min = this.system.curseMin;
    const cur = clampNumber(this.system?.curseCount, 1, 6, 1);
    // If the database has less than min, persist the minimum.
    if (cur < min) {
      await this.update({ "system.curseCount": min });
    }
  }

  getRollSources() {
    const bgMap = buildLocalizedOptionsMap(OPTIONS_BACKGROUND);
    const prideMap = buildLocalizedOptionsMap(OPTIONS_PRIDE);
    const onmyoujiMap = buildLocalizedOptionsMap(OPTIONS_ONMYOUJI);

    // system.backgrounds is a Set natively generated by SetField
    // Filter out any undefined/null/empty values that may remain from legacy data
    const backgrounds = Array.from(this.system?.backgrounds ?? []).filter(v => typeof v === "string" && v.length);
    const prides = Array.from(this.system?.prides ?? []).filter(v => typeof v === "string" && v.length);
    const onmyoujis = Array.from(this.system?.onmyoujis ?? []).filter(v => typeof v === "string" && v.length);
    const curseCount = clampNumber(this.system?.curseCount, 0, 6, 0);

    const bonusSources = [
      ...backgrounds.map((value) => ({
        id: `background::${value}`,
        value,
        kind: "background",
        badge: game.i18n.localize("OCHO.Sections.Background"),
        label: bgMap.get(String(value)) ?? String(value)
      })),
      ...prides.map((value) => ({
        id: `pride::${value}`,
        value,
        kind: "pride",
        badge: game.i18n.localize("OCHO.Sections.Pride"),
        label: prideMap.get(String(value)) ?? String(value)
      }))
    ];

    const cursedSources = [];
    if (curseCount > 0) {
      cursedSources.push({
        id: "curse::Maldición",
        value: "Maldición",
        kind: "curse",
        badge: game.i18n.localize("OCHO.Sections.Curse"),
        label: game.i18n.localize("OCHO.Roll.CurseSource")
      });
    }
    cursedSources.push(
      ...onmyoujis.map((value) => ({
        id: `onmyouji::${value}`,
        value,
        kind: "onmyouji",
        badge: game.i18n.localize("OCHO.Sections.Onmyoujis"),
        label: onmyoujiMap.get(String(value)) ?? String(value)
      }))
    );

    return { bonusSources, cursedSources };
  }

  async rollRisk() {
    await this.enforceCurseMin();
    const { bonusSources, cursedSources } = this.getRollSources();

    const dialogData = await openRollDialog({
      rollType: "risk",
      flavor: "",
      actorName: this.name,
      bonusSources,
      cursedSources
    });
    if (!dialogData) return;

    const {
      rollType,
      flavor,
      useBonus,
      useCursed,
      selectedBonusSources = [],
      selectedCursedSources = []
    } = dialogData;

    if (rollType === "curse") {
      await rollCurse(this, { fromRisk: false, subtitle: flavor });
      return;
    }

    const title = game.i18n.localize("OCHO.Roll.Type.Risk");
    const whiteDice = Math.min(2, 1 + (useBonus ? 1 : 0));
    const diceExprs = [];
    for (let i = 0; i < whiteDice; i++) diceExprs.push("1d6[Blanco]");
    if (useCursed) diceExprs.push("1d6[Maldito]");

    const formula = diceExprs.length > 1 ? `{${diceExprs.join(",")}}kh1` : diceExprs[0];
    const riskRoll = new Roll(formula);
    applyCursedAppearance(riskRoll);
    await riskRoll.evaluate();
    applyCursedAppearance(riskRoll); 

    const diceForCard = [];
    const whiteValues = [];
    let cursedValue = null;

    const DieTerm = foundry.dice.terms.Die;
    const collectDiceTerms = (term) => {
      if (!term) return [];
      if (term instanceof DieTerm) return [term];
      const inner = term.terms ?? term.dice ?? [];
      if (!Array.isArray(inner)) return [];
      return inner.flatMap(collectDiceTerms);
    };

    const diceTerms = (riskRoll.dice && riskRoll.dice.length) ? riskRoll.dice : (riskRoll.terms ?? []).flatMap(collectDiceTerms);

    let whiteIndex = 0;
    for (const d of diceTerms) {
      const flavorTag = String(d.options?.flavor ?? "").toLowerCase();
      const isCursed = flavorTag.includes("maldito");

      for (const r of (d.results ?? [])) {
        const v = Number(r?.result ?? r ?? 0);
        if (!Number.isFinite(v)) continue;

        if (isCursed) {
          cursedValue = v;
          diceForCard.push({
            label: game.i18n.localize("OCHO.Roll.CursedDie"),
            result: v,
            css: "ol-die-cursed"
          });
        } else {
          whiteIndex += 1;
          whiteValues.push(v);
          const dieLabel = whiteIndex === 1
            ? game.i18n.localize("OCHO.Roll.BaseWhiteDie")
            : game.i18n.localize("OCHO.Roll.BonusWhiteDie");
          diceForCard.push({
            label: dieLabel,
            result: v,
            css: whiteIndex === 1 ? "ol-die-white" : "ol-die-white ol-die-white-bonus"
          });
        }
      }
    }

    const bestWhite = whiteValues.length ? whiteValues.reduce((m, v) => (v > m ? v : m), 0) : 0;
    const best = Math.max(bestWhite, Number(cursedValue ?? 0));
    const classification = classifyResult(best);
    const classificationCss = classifyResultCss(best);
    const curseTriggered = Boolean(useCursed && cursedValue !== null && bestWhite > 0 && Number(cursedValue) >= bestWhite);

    await sendRollToChat({
      actor: this,
      rolls: [riskRoll].filter(Boolean),
      title,
      flavor,
      dice: diceForCard,
      bestWhite,
      cursedValue,
      best,
      classification,
      classificationCss,
      curseTriggered,
      selectedBonusSources,
      selectedCursedSources
    });
  }

  async purifyCharacter() {
    await this.enforceCurseMin();

    const curMin = this.system.curseMin;
    const cur = Math.max(curMin, Number(this.system?.curseCount ?? curMin));

    if (cur < 4) {
      ui.notifications?.warn?.(game.i18n.localize("OCHO.Purify.ErrorTooLow"));
      return;
    }

    const sceneId = canvas?.scene?.id ?? game.scenes?.current?.id ?? null;
    const lastScene = this.getFlag("ocho-lanzas", "purifySceneId") ?? null;
    if (sceneId && lastScene === sceneId) {
      ui.notifications?.warn?.(game.i18n.localize("OCHO.Purify.ErrorOncePerScene"));
      return;
    }

    const content = await foundry.applications.handlebars.renderTemplate(
      "systems/ocho-lanzas/templates/dialogs/purify-dialog.hbs",
      {}
    );

    const DialogV2 = foundry.applications.api.DialogV2;
    const result = await DialogV2.prompt({
      window: { title: game.i18n.localize("OCHO.Purify.Title") },
      classes: ["ocho-lanzas", "ol-purify-dialog-v60"],
      content,
      ok: {
        label: game.i18n.localize("OCHO.Purify.Confirm"),
        callback: async (_event, _button, dialog) => {
          const form = dialog.element.querySelector("form");
          const fd = new FormData(form);
          return { consequence: String(fd.get("consequence") ?? "").trim() };
        }
      },
      cancel: { label: game.i18n.localize("OCHO.Purify.Cancel") },
      rejectClose: false
    });

    if (!result) return;

    if (!result.consequence?.length) {
      ui.notifications?.warn?.(game.i18n.localize("OCHO.Purify.ErrorConsequenceRequired"));
      return;
    }

    await purify(this, { consequence: result.consequence });
  }
}
